---
version: '3.3'
services:
  pktvisor-pop1:
    image: pktvisor:latest-withtelegraf
    build: ./with_telegraf
    volumes:
      - './config/telegraf-pop1.conf:/etc/telegraf/telegraf.conf:ro'
  pktvisor-pop2:
    image: pktvisor:latest-withtelegraf
    build: ./with_telegraf
    volumes:
      - './config/telegraf-pop2.conf:/etc/telegraf/telegraf.conf:ro'
  elasticsearch:
    image: elasticsearch:7.9.3
    environment:
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - 'discovery.type=single-node'
  kibana:
    image: kibana:7.9.3
    environment:
      - 'ELASTICSEARCH_HOSTS=http://elasticsearch:9200'
    ports:
      - '5601:5601'
  grafana:
    image: grafana/grafana:7.3.0
    ports:
      - '3000:3000'
